# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCapgeminiMobileFactory2020VIPER' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestCapgeminiMobileFactory2020VIPER
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher'
end
